#!/usr/bin/env zsh
haveProg() {
    [ -x "$(which $1)" ]
}

if haveProg apt ; then 
  export PKG_MANAGER='apt'
  alias pkgInstall="sudo ${PKG_MANAGER} install"
elif haveProg yum ; then 
  export PKG_MANAGER='yum'
  alias pkgInstall="sudo ${PKG_MANAGER} install"
elif haveProg yay ; then 
  export PKG_MANAGER='yay'
  alias pkgInstall="sudo ${PKG_MANAGER} -S"
elif haveProg pacman ; then 
  export PKG_MANAGER='pacman'
  alias pkgInstall="sudo ${PKG_MANAGER} -S"
else
    echo 'No package manager found!'
    exit 2
fi
