#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
  ffmpeg="ffmpeg -hide_banner"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}

alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias vim='nvim'
alias v='nvim'
# enable color support of ls and also add handy aliases
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto -n'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias la='ls -Alh' # show hidden files
alias ls='ls -aFh --color=always' # add colors and file type extensions
alias lx='ls -lXBh' # sort by extension
alias lk='ls -lSrh' # sort by size
alias lc='ls -lcrh' # sort by change time
alias lu='ls -lurh' # sort by access time
alias lr='ls -lRh' # recursive ls
alias lt='ls -ltrh' # sort by date
alias lm='ls -alh |more' # pipe through 'more'
alias lw='ls -xAh' # wide listing format
alias ll='ls -Fls' # long listing format
alias labc='ls -lap' #alphabetical sort
alias lf="ls -l | egrep -v '^d'" # files only
alias ldir="ls -l | egrep '^d'" # directories only
alias bd='cd "$OLDPWD"'
alias sha1='openssl sha1'
alias ezrc='chezmoi edit ~/.zshrc'
# Add an "alert" alias for long running commands.  Use like so:
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias mlab="matlab -nodesktop -nosplash"
# Useful aliases
alias ports='netstat -tulanp'
alias h='history'
alias j='jobs -l'
alias diff='colordiff'
alias mount='mount |column -t'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias e='env|grep -Ei'
alias c='clear'
alias ping='ping -c 5' # ping aliases Stop after sending count ECHO_REQUEST packets #
alias fastping='ping -c 100 -s.2' # Do not wait interval 1 second, go fast #
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias df='df -h'
alias du=dirsize
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p -v'
alias biggest='BLOCKSIZE=1048576; du -x | sort -nr | head -10'
# Android Dev aliases
alias adb='sudo adb'
alias adbr='adb kill-server; adb start-server'
alias studio='/usr/local/bin/studio . & '
#BoxSync alias
alias box='~/repos/box-linux-sync/bin/box-sync'
#Conda aliases
alias aenv='conda activate'
alias denv='conda deactivate'
alias tfclone='conda create --clone tf_build --name'
#Other aliases
alias rst='antigen reset; exec zsh'
alias zen='python -c "import this"'
alias xopen='xdg-open'
#git aliases
alias g='git'
alias gch=' git checkout'
alias gco='git commit'
alias gcl='git clone'
alias gd='git diff'
alias gs='git status -sb'
#alias gi='git ignore'
alias ga='git add'
alias gp='git push'
alias addr='ifconfig | grep "inet addr" -m 1'
alias chr='nohup google-chrome'
alias gA='git add -A'
alias jnbs="jupyter notebook --no-browser --port=8889"
alias killgazebogym='killall -9 rosout roslaunch rosmaster gzserver nodelet robot_state_publisher gzclient'
#alias bc='bc -l'
alias cm='chezmoi'
alias cmd='chezmoi diff | colordiff'
alias cma='chezmoi apply -v'
alias e=cedit
alias z='zathura'

startNeurosurgeon(){
  cd ~/repos/neurosurgeon/object_detection
  aenv ns
  python udp_testing.py
}

if [[ "$(hostname -s)" == "noahserver" ]]; then
  alias ns=startNeurosurgeon
fi
