#!/usr/bin/env bash
count=0
disconnected="%{F#cb4b16} "
disconnected1="%{F#dc322f} Wireless Off"
wireless_connected="%{F#859900} "
ethernet_connected="%{F#859900} "

SSID_NAME=$(iw dev | grep ssid | awk '{print $2}')
ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 25
        else
            echo "$wireless_connected" "${SSID_NAME}"; sleep 5
        fi
    else
      if [[ "$(ip link | awk '/UP/ {print $2}'| wc -l)" == 2 ]]; then
        echo "$disconnected1"; sleep 0.5
      else
        echo "$disconnected"; sleep 0.5
      fi
    fi
done
